### ISSUE TITLE
Add a card to the skill response

### ISSUE THREAD

**Issue by gitrago** [balsimpson/alexa-radio#1]
Is there a trivial way to add a card to the skill response so the skill can be seen in Activity and possibly activated from a screen too?

I found this in **Alexa.js** but it does not seem to work:

```
 withSimpleCard: (title, content, image_url) => {
    return {

      "type": "Standard",
      "title": `${title}`,
      "content": `${content}`,
      "text": `${content}`,
      "image": {
        "smallImageUrl": `${image_url}`,
        "largeImageUrl": `${image_url}`
      }
    }
  },
```

**Comment by balsimpson** [comment]
Did you add it like this?

```
response.speak = Alexa.speak(`some text output`);
response.card = Alexa.withSimpleCard(`some title`, 'some content', 'some url);

return Alexa.getResponse(response);
```

**Comment by gitrago** [comment]
I am not sure where to put that. It seems to be already there:
https://github.com/balsimpson/alexa-radio/blob/32b913f667a65104a8929b991aac02c84025ea9b/functions/alexa.js#L73
yet playing radio does not show up in my Activity history on the Alexa app. Is this a problem on my end?

**Comment by balsimpson** [comment]
This is something that confused me too when I was starting out. The function on line 73 is the function definition. You need to invoke the function to use it.
https://github.com/balsimpson/alexa-radio/blob/32b913f667a65104a8929b991aac02c84025ea9b/functions/alexa.js#L73

Below are the two times it is invoked. 
https://github.com/balsimpson/alexa-radio/blob/32b913f667a65104a8929b991aac02c84025ea9b/functions/alexa.js#L218

https://github.com/balsimpson/alexa-radio/blob/32b913f667a65104a8929b991aac02c84025ea9b/functions/alexa.js#L283

To send a card, you can add the card function just above the lines indicated above (line 218 and line 283). so it would look like:

```
response.card = Alexa.withSimpleCard(`some title`, 'some content', 'some url);
return Alexa.getResponse(response);
```

**Comment by balsimpson** [comment]
Closing issue
