### ISSUE TITLE
Audio Player hearing no Sound

### ISSUE THREAD

**Issue by FD20201** [balsimpson/alexa-radio#27]
Hello Guys, i have tested my skill on an Echo and an Fire TV Stick.
On both devices when i start my Skill it says that i am listening to it but no sound cames.
It says taht i am listening to it but i didnt hear my stream or anything.
Could you please help me

**Comment by balsimpson** [comment]
Are you able to play the file directly in your browser when you go to the station URL?

**Comment by FD20201** [comment]
I got this to work. Another thing Balsimpson.
Is there any way to show the metadata and the actual title art (that were given from an url(given by server) in the audio player?

**Comment by balsimpson** [comment]
Am glad you got it to work. But I was not able to find any way to show the URL metadata as it doesn't register as an event on the code when it changes tracks. Same reason you can't skip next or go back.
