### ISSUE TITLE
No Channel

### ISSUE THREAD

**Issue by pmscloudeu** [balsimpson/alexa-radio#3]
Hi, when I click on + CHANNEL, nothing happens.
Tx

<img width="586" alt="1" src="https://user-images.githubusercontent.com/44649340/72435195-30bccd80-37a6-11ea-9515-2ab488731776.PNG">

**Comment by balsimpson** [comment]
that's strange. could you please share the link? also please try it on a different browser.

**Comment by pmscloudeu** [comment]
Hi

 

Yes I have tried on 3 different browsers.

 

https://freaklike.api.stdlib.com/alexa-radio@dev/

 

Thanks

**Comment by balsimpson** [comment]
To fix it:
Go to `index.html` on [stdlib.com](https://code.stdlib.com)
Go to function `getItems`
Remove the front slash from '/stations' in `url: user_collection_url + '/stations',`.

```
axios({
  url: user_collection_url + '/stations',
  method: "GET"
})
```



it should be now:
```
axios({
  url: user_collection_url + 'stations',
  method: "GET"
})
```

deploy the code.

please let me know if this helps and i'll update the code accordingly

**Comment by pmscloudeu** [comment]
Unfortunately that didn't work. Nothing happens when I click on channels and also when I click on settings

**Comment by balsimpson** [comment]
great.
