### ISSUE TITLE
Missing file AlexaSkillCode.zip

### ISSUE THREAD

**Issue by freqq68** [balsimpson/alexa-radio#33]
Hello @balsimpson 

In your Tutorial it seem's to find a file in the root folder: 
![image](https://github.com/balsimpson/alexa-radio/assets/4027268/8d0ddd29-b8de-45ef-8bf3-74ba16c262bb)

And I don't find this file :)

Is there a way ti find it ? 

Thank's !

**Comment by balsimpson** [comment]
Am sorry, but I don't think this works anymore.

**Comment by freqq68** [comment]
Okay thank's for your reply. no worries, I have stopped the project now ^^
