### ISSUE TITLE
blank screen in stdlib

### ISSUE THREAD

**Issue by fpscan** [balsimpson/alexa-radio#7]
Is it just me or everyone else having issue with stdlib, when I click the deploy button it just open a blank screen.

**Comment by balsimpson** [comment]
I was also having some problems for a short time, but it seems to be working now.

**Comment by fpscan** [comment]
@balsimpson hi, thank you for quick respond, it started for first time but it's failing right now.

**Comment by balsimpson** [comment]
`Unsupported Directive AudioPlayer is currently an unsupported namespace. Check the device log for more information.` - you will get this warning when you test it on developer console. The audio will stream only on actual devices.

**Comment by fpscan** [comment]
Ah, sorry, I never get this notification. I've tried with my real Alexa devices. 
![IMG_4559](https://user-images.githubusercontent.com/4651944/74061577-5f247600-49fd-11ea-9c11-ec7933e6e60a.jpg)
![IMG_4558](https://user-images.githubusercontent.com/4651944/74061579-6055a300-49fd-11ea-8158-dbcc610d7e2f.jpg)
